//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyber20ShadowServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsMonitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsMonitor()
        {
            this.ClientsMonitorOriginTables = new HashSet<ClientsMonitorOriginTable>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ClientName { get; set; }
        public string ClientIP { get; set; }
        public string ClientMAC { get; set; }
        public string LogedInUser { get; set; }
        public string ClientStatus { get; set; }
        public string CertificateStatus { get; set; }
        public string WhiteListVersion { get; set; }
        public string ConnectionStatus { get; set; }
        public string UIVersion { get; set; }
        public string DriverVersion { get; set; }
        public string ClientOSVersion { get; set; }
        public string LogSenderVersion { get; set; }
        public string SUPVersion { get; set; }
        public string ServiceVersion { get; set; }
        public string ReconnaissanceVersion { get; set; }
        public Nullable<int> IsScrambled { get; set; }
        public string LastWhiteListDataInsert { get; set; }
        public string ClientDescription { get; set; }
        public string ClientGroup { get; set; }
        public Nullable<int> ServerID { get; set; }
        public Nullable<int> IsScrambledRequired { get; set; }
        public string GUID { get; set; }
        public string LastCertificateUpdate { get; set; }
        public string LastWhiteListUpdate { get; set; }
        public string UniqueID { get; set; }
        public string CurrentPublicKey { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsMonitorOriginTable> ClientsMonitorOriginTables { get; set; }
    }
}
